config/routes.rb
RailsHn::Application.routes.draw do
  

  root to: 'links#index'

  resources :users do
    resources :comments
  end

  resources :links do
    resources :comments
    resources :votes do
      post :update, on: :member
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :votes

  match '/signup',  to: 'users#new',            via: [:get]
  match '/signin',  to: 'sessions#new',         via: [:get]
  match '/signout', to: 'sessions#destroy',     via: [:get]

  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :commentable, polymorphic: true
    belongs_to :user
end

app/models/link.rb
class Link < ActiveRecord::Base
    
    has_many :votes
    belongs_to :user

    validates :title, presence: true
    validates :url, presence: true
    validates :description, presence: true, length: { minimum: 6 }

    has_many :comments, as: :commentable

    def self.order_by_votes(current_user_id)
        current_user_id ||= "null"
        joins('left join votes on links.id = votes.link_id')
        .select("links.*, coalesce(sum(votes.value),0) as votes_total, " <<
        "sum(case votes.user_id when #{current_user_id} then votes.value "<<
        "else 0 end) as user_votes_total").group("links.id")
        .order('votes_total DESC').paginate(page: 1, per_page: 10)
    end


end

app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password

    has_many :links
    has_many :votes
    has_many :comments
    # has_many :comments, as: :commentable
    before_save { self.email = email.downcase }
    before_create :create_remember_token
    

    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, length: { minimum: 6 }
    validates :password_confirmation, presence: true



    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

      

    private
        def create_remember_token
            self.remember_token = SecureRandom.urlsafe_base64
        end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :link

    def self.record_user_vote(link_id, user_id, vote_code)
        vote = find_or_initialize_by( link_id: link_id, user_id: user_id)
        case vote_code.to_i
            when 1
                vote.value = -1
            when 2
                vote.value = 1
            when 0
                vote.value = 0
            end
            vote.save
    end

    def votes_with_totals
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable

  def index
    @comments = @commentable.comments.order()
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    # received_params = params.permit!
    # use_params = received_params["comment"]
    # puts "PARAMETERS RECIEVED" + use_params.to_s
    @comment = @commentable.comments.new(params.require(:comment).permit(:content))
    @comment.user_id = current_user.id
    @comment.save
    respond_to do |format|
      format.html {redirect_to @commentable,  notice: "Comment created."}
      format.js
    end
end


  def load_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :new, :update]

  def index
      @links = Link.order_by_votes current_user.try(:id)
  end

  def new
    @link = Link.new
  end

  def show
    @link = Link.where(id: params[:id]).take
    @commentable = @link
    @comments = @commentable.comments.includes(:user).order("created_at ASC")
    @comment = Comment.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
        flash[:success] = "Link saved!"
        redirect_to root_path
    else
        # There was an error, re-render error partial will display
        render 'new'
    end

  end

  def update
    @link = Link.new
  end

  private

    def link_params
        params.require(:link).permit(:title, :url, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        @commentable = @link
      @comments = @commentable.comments
      @comment = Comment.new
    end

    def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      #error occured, form will re-render with errors
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :signed_in_user, only: [:update]

    def new
    end

    def show
    end

    def update
            @vote = Vote.record_user_vote(params[:link_id], current_user.id, params[:id])
            
            respond_to do |format|
                format.html { redirect_to(root_path) }
                format.json { render json: {success: true, redirect: false} }
            end

            rescue ActiveRecord::RecordInvalid
                respond_to do |format|
                    format.html do
                        flash[:error] = 'Vote error'
                        redirect_to(root_path)
                    end
                    format.json { render json: {success: false, redirect: false} }
                end
            end

    end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !self.current_user.nil?
  end


  def signed_in_user
    unless signed_in?
      @sign_in_message = "Sorry! You must be signed in to do that."
      respond_to do |format|
        format.html {redirect_to signin_url, notice: @sign_in_message}
        format.json do
          flash[:notice] = @sign_in_message
          render json: {success: false, redirect: signin_path}
        end
      end 
  end
      
end

  
  

 def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for [@commentable, @comment], remote: true do |f| %>
<% if @comment.errors.any? %>
<div class="error_messages">

    <h2>Please correct the following errors.</h2>
    <ul><% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %>
            <% end %>
    </ul>
</div>
<% end %>

<div class="form-group" >
<%= f.label :comment, class: "control-label" %>
<%= f.text_area :content, rows: "3", class: "form-control" %>
</div>

<div class="form-group">
    <%= f.submit "Create", class: "btn btn-large btn-primary" %>
</div>
<% end %>

app/views/comments/_comment_index.html.erb
<h4>Comments</h2>
<div id="comments" class="well">
<% @comments.each do |comment| %>
<div class = "comment">
    <%= comment.content %> -- <b><%= link_to comment.user.name, comment.user %> </b> <span class="comment-date"> <%= comment.created_at.strftime("%d %b. %Y") %> at <%= comment.created_at.strftime("%H:%M") %></span>
</div>
<% end %>


</div>

app/views/comments/create.js.erb
$('#comments').append('<div id="comment"><%= @comment.content %> -- <b><%= link_to @comment.user.name, @comment.user %> </b> <span class="comment-date"> <%= @comment.created_at.strftime("%d %b. %Y") %> at <%= @comment.created_at.strftime("%H:%M") %></span></div>')

app/views/comments/index.html.erb
<h1>Comments index</h1>

<%= render 'comment_index' %>

<p><%= link_to "New Comment", [:new, @commentable, :comment] %>

app/views/comments/new.html.erb
<h1>New Comment</h1>


<%= render 'comment_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RAILS HN</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
</head>

<body data-no-turbolink>
<%= render "shared/header" %>
    
    <div class="container">
      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-xs-8 col-sm-offset-2" border="1px solid">
            <% flash.each do |key, value| %>
              <div class="<%= flash_class(key) %>">
              <%= value %>
              </div>      
            <% end %>
            <%= yield %>
        </div>
      </div>
    </div>
  </div>

    



<%= render "shared/footer" %>
   
</body>
</html>

app/views/links/index.html.erb
<div class="col-md-12 centered">

<table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Vote!</th>
                    <th>Links</th>
                  </tr>
                </thead>
                <tbody>
                    <% @links.each do |link| %>
                  <tr id="<%= link.id %>">
                    <td style="text-align:center">
                    <div>
                      <form action="<%= link.user_votes_total==1 ? "/links/" + link.id.to_s + "/votes/0" : "/links/" + link.id.to_s + "/votes/2" %>" method="post">
                      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
                    <button type="submit" id="<%= link.id %>" class="btn btn-default vote-up glyphicon glyphicon-chevron-up <%= link.user_votes_total==1 ? "vote-up-on" : "" %>">
                    </button>
                    </form>
                  </div>
                  <div>
                        <form action="<%= link.user_votes_total==-1 ? "/links/" + link.id.to_s + "/votes/0" : "/links/" + link.id.to_s + "/votes/1" %>" method="post">
                          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
                          <button type="submit" id="<%= link.id %>" class="btn btn-default vote-down glyphicon glyphicon-chevron-down <%= link.user_votes_total==-1 ? "vote-down-on" : "" %>">
                          </button>
                        </form>
                  </div>
                </td>
                    <td style="vertical-align:middle;">
                  <span class="badge"><%= link.votes_total %></span>
                  <p><%= link_to link.title, link %>- <%= link.description %></p></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>

                  <%= will_paginate %>


</div>

app/views/links/new.html.erb
<%= provide(:title, "New Link") %>
<h1>New Link</h1>
<%= form_for @link do |f| %>
        <div class="form-group">
            <%= render 'shared/link_error_messages', object: @user %>
            <%= f.label :title, class: "control-label" %>
             <%= f.text_field :title, class: "form-control"%> 
        </div>

        <div class="form-group">
            <%= f.label :url, class: "control-label" %>
            <%= f.text_field :url, class: "form-control"%>
        </div>

        <div class="form-group">
            <%= f.label :description, class: "control-label" %> 
            <%= f.text_area :description, rows: "3", class: "form-control" %>
       </div>

        <div class="form-group">
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    </div>
<% end %>

app/views/links/show.html.erb
<div class="col-md-12 centered">

    <h1><%= link_to @link.title %></h1>
    <p><%= @link.description %></p>

    <%= render "comments/comment_index" %>
    <%= render "comments/comment_form" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
      <p>&copy;Rails Hacker News 2013</p>
    </div>
  <%= debug(params) if Rails.env.development? %>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Rails Hacker News!</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>

            <li><a href=<%= new_link_path %>>Post</a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="themes">
                <li><a tabindex="-1" href=<%= signout_path %>>Sign Out</a></li>
              </ul>
            </li>
            
            <% else %>
              <li><a href=<%= signin_path %>>Sign In</a></li>
            <% end %>


          </ul>

        </div>
      </div>
    </div>

app/views/shared/_link_error_messages.html.erb
<% if @link.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@link.errors.count, "error") %>.
    </div>
    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>


    <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= render 'shared/error_messages', object: @user %>
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "control-label" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password, class: "control-label" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: "control-label" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    </div>

    <% end %>

app/views/votes/update.js.erb
alert('hello')